<a href="https://colab.research.google.com/github/carloscesar182/ai_advanced_course/blob/main/Notebooks/PythonFundamentals/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importar a biblioteca
import numpy as np

In [3]:
# cria uma matriz unidimensional usando numpy
mt = np.array([12, 34, 26, 18, 10]) # parenteses pq estou usando o metodo array do numpy e colchetes pq estou passando um vetor de dados
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
# criar o array com um tipo específico (float de 64 bits)
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

# criar o array com int32
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))


[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# mudar o tipo de array
# podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)

# quando transformamos de float pra int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [7]:
# podemos também fazer o inverso
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [8]:
# matrizes bidimensionais do numpy
mt7 = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [10]:
# criar arrays vazios tipificados
# empty significa que não são inicializados, não que são vazios
vazio = np.empty([3, 2], dtype = int)
print(vazio)
print("-------")

# criar uma matriz 4x3 com valores 0
# numa matriz, o primeiro numero são as linhas e o segundo as colunas
zeros = np.zeros([4, 3])
print(zeros)
print("-------")

# com valores igual a 1
um = np.ones([5, 7])
print(um)
print("-------")

# criar uma matriz com diagonal principal com valores 1 e outros com valores 0
diagonal = np.eye(5)
print(diagonal)

[[      115090931               0]
 [134938819439792 134938819441584]
 [134938819440368 134938819454144]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# criar valores aleatórios entre 0 e 1
ale = np.random.random((5))
print(ale)
print("-------")

# criar valores aleatórios com distribuição normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("-------")

# valores aleatórios 3 x 4
ale3 = (10 * np.random.random((3, 4)))
print(ale3)
print("-------")

[0.26525164 0.3233141  0.00708441 0.06980695 0.30511276]
-------
[-1.09968001 -0.18811237  0.1532894  -0.91470553  1.0553154 ]
-------
[[5.87999547 5.13246006 0.41733085 5.1051081 ]
 [5.74341909 2.79782736 9.41958192 0.44526087]
 [8.37039606 7.49836789 4.90255788 1.75876628]]
-------


In [12]:
# outras formas de gerar valores aleatórios
# uso de sementes
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

# gerar inteiros
ale6 = gnr.integers(10, size = (3, 4)) # gera inteiros até 10 numa matriz de 3 linhas e 4 colunas
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [13]:
# unique remove repetições
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [14]:
# funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43], [27,25,14], [15,24,32]])

# mostra a matriz k
print(k)

# mostra um elemento específico da matriz k
print(k[0][1]) # elemento [0] é a linha, [1] é a coluna

# mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [15]:
# funções matemáticas
# mostra o maior valor da matriz k
print(k.max())

# mostra o menor valor da matriz k
print(k.min())

# mostra a soma dos valores da matriz k
print(k.sum())

# mostra o valor da média dos valores da matriz k
print(k.mean())

# mostra o valor do desvio padrão (std - standard deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [18]:
# funções universais aplicadas a todos os elementos
# mostra o valor da raiz quadrada de todos os elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

# mostra o valor do exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [21]:
# extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])

# mostra o elemento na posição 2
print(m[1])
print("-------")

# mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")

# mostra o array criado a partir da 2a posição até todo o restante do array
print(m[1:])
print("-------")

# mostra o array criado a partir do antipenultimo até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [23]:
# extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-------")

# primeiro linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")

# segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")

# terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")

# todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-------")

# todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


In [30]:
# adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

res1 = n+0
print(res1)
print("-------")

res2 = n*0
print(res2)
print("-------")

p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
res3 = p+q
print(res3)

[[1 2]
 [3 4]]
-------
[[0 0]
 [0 0]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [40]:
# transposição (pivotar)
# muda o arranjo de uma matriz
f = np.arange(15).reshape((3, 5))

# mostra a matriz transposta entre linha e coluna
print(f)
print("-------")
s = f.T # método T faz a transposição
print(s)
print("-------")

# outra forma de fazer usando o método transpose
r = np.arange(10).reshape((2, 5))
print(r)
print("-------")
s = r.transpose((1, 0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
-------
[[0 1 2 3 4]
 [5 6 7 8 9]]
-------
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [42]:
# expressões lógicas
# usando where

# criar uma matriz aleatória com valores positivos e negativos
v = np.random.randn(4, 4)
print(v)

# criar uma matriz com valores booleanos baseado no array v
x = (v > 0) # aqui já dá True ou False pq x recebeu um valor de teste lógico
print(x)

# criar uma matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.6174008  -2.64983958 -1.14042237  1.22039752]
 [ 0.71730067  0.99864739 -0.73174857  0.28568728]
 [-1.91700893  0.61687086 -0.46704194 -1.25768791]
 [-0.73967661 -0.58381335  1.93159243  0.85993955]]
[[ True False False  True]
 [ True  True False  True]
 [False  True False False]
 [False False  True  True]]
[[ 1 -1 -1  1]
 [ 1  1 -1  1]
 [-1  1 -1 -1]
 [-1 -1  1  1]]
