<a href="https://colab.research.google.com/github/carloscesar182/ai_advanced_course/blob/main/Notebooks/MLAlgorithms/kNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [ ]:
mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()

In [ ]:
# criar as variáveis indepentes
# vamos usar o mpg (consumo), hp (potencia) pra prever o cyl (num cilindros)
X = mtcars[['mpg', 'hp']].values
y = mtcars['cyl'].values

In [ ]:
# implementação do knn
knn = KNeighborsClassifier(n_neighbors=3)
modelo = knn.fit(X, y)
modelo

In [ ]:
# criar o modelo da previsão
y_prev = modelo.predict(X)
print(y_prev)

In [ ]:
# metricas
accuracy = accuracy_score(y, y_prev)
precision = precision_score(y, y_prev, average='weighted')
recall = recall_score(y, y_prev, average='weighted')
f1 = f1_score(y, y_prev, average='weighted')
cm = confusion_matrix(y, y_prev)

print(f'Acurácia: {accuracy}')
print(f'Precisão: {precision}')
print(f'Recall: {recall}')
print(f'F1: {f1}')
print(f'Matriz de confusão: \n{cm}')

Acurácia: 0.9375
Precisão: 0.9395833333333333
Recall: 0.9375
F1: 0.9372947454844006
Matriz de confusão: 
[[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [ ]:
# criar um novo conjunto de dados apenas com 1 registro pra fazer a previsão
# olhar a disntancia e os indices (posições dos registros que o modelo definiu como vizinhos mais proximos)

# mpg e hp
new_data = np.array([[19.3, 105]])

previsao = modelo.predict(new_data)
print(previsao)

distances, indices = modelo.kneighbors(new_data)
print(distances)
print(indices)
# cyl

In [ ]:
# ver os registos
mtcars.loc[[1,5,31], ["cyl", "mpg", "hp"]]

cyl   mpg   hp
1     6  21.0  110
5     6  18.1  105
31    4  21.4  109